### PR TITLE
Preserve request

### PR DESCRIPTION
**Pull request by jschlies**
Preserve request to provide context to call to failureCallback in addressQuickVerify()

### CODE REVIEW

**Comment by scottconnerly** [comment]
Please remove the example failureCallback from the config file.

Also, the new $this->previous_request isn't being passed into either failureCallback. Did you want it in either?

**Comment by jschlies** [comment]
Thanks for the feedback. I have added  $this->prev_request to both calls to this->failureCallback howvver the prder of the params (within the array) seem inconsistent, ($curl_info). Is this on purpose??? I'd be happy to whistle past the graveyard on this but I want it to be consistent and I want to minimally impact on others with already defined this->failureCallback's.

**Comment by scottconnerly** [comment]
I'll call it intentionally not over-engineered :)

**Comment by jschlies** [comment]
thks

**Pull request merged**
