### PR TITLE
update to L6 and PHP7.2

### PR DESCRIPTION
**Pull request by scs-ben**

### CODE REVIEW

**Comment by tecshaun** [comment]
I'd love this PR to be merged as we can't use Laravel 6 without it

**Comment by scs-ben** [comment]
You can do what we're doing and use my forked branch until this repo is updated:
https://github.com/scs-ben/smartystreets-laravel

**Comment by tecshaun** [comment]
Thanks!

Sorry how would I pull this in composer? I've never done a forked version of a package into composer.

**Comment by scs-ben** [comment]
You just add a section to your composer.json file:
`"repositories": [
        {
            "type": "git",
            "url": "https://github.com/scs-ben/smartystreets-laravel"
        }
    ],`

Leave everything else the same and you're fine

**Comment by tecshaun** [comment]
Thanks so much for your help - that worked :)

**Pull request closed without merging**
